### ISSUE TITLE
Provide one or more output values from the mainTemplate

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#13]
It could be a good idea to provide a few output values from the mainTemplate. For example, the public IP FQDN of the main node that was created.

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L579

You can probably feed it back from the nested template since you already have it there
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/publicIP-single.json#L241

**Comment by btprabhu** [comment]
Done
