### ISSUE TITLE
Do OS disk storage and data disk storage account names same?

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#16]
This seems to be using same naming convention as used by the storage-new.json

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/database-Standard_D4_v2.json#L181

Are they meant to be the same? It would make sense that yes, since you would not want to create 2x more storage accounts.

It looks like you are using the same storage accounts for the OS disks:
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/database-Standard_D4_v2.json#L298

What is the purpose of the storage-new.json template?

In the future, this whole thing will be easier once we use Managed Disks.

**Comment by btprabhu** [comment]
New storage-new.json will create new osStorage account and in they are refereed same as in nested template. They are not created in it.

* Name for data disk and osStorage account are different.
