### ISSUE TITLE
Remove sample commandToExecute from outputs of VMs

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#18]
I think this is here just for testing. We will need to remove it from here since it contains secure strings (like passwords) that you don't want to persist:

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/database-Standard_D4_v2.json#L388

**Comment by btprabhu** [comment]
Done
