### ISSUE TITLE
What do the SMP templates represent exactly?

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#19]
For example: https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L201

I tried WinMerge on two sample templates and see almost no difference, except for some spacing. Therefore, highly recommend to do reformatting using Visual Studio so that all your code looks same in all files. See example comparison:

![image](https://cloud.githubusercontent.com/assets/1821568/20110172/dde19006-a5a8-11e6-8a7c-e50ad2a6b000.png)

If SMP templates are truly identical, I would recommend removing them to minimize clutter and making it easier to review the submission package later.

**Comment by btprabhu** [comment]
For market place solution they are not required so we also removed it from solution.
