### ISSUE TITLE
DS15_v2 template is difference from others

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#20]
There is a big difference between the DS15_v2 template and other templates.

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/database-Standard_DS15_v2.json#L276

In DS15_v2 you are still using custom image instead of the marketplace image. This is probably because for now these templates are not yet used, but I wanted to make sure you are aware.

**Comment by btprabhu** [comment]
Update it done.
