### ISSUE TITLE
What are dataDisks used for in D4 deployment?

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#21]
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/database-Standard_D4_v2.json#L303

**Comment by btprabhu** [comment]
Arsen, Currently the D4 SKU uses 512 GB storage size, 2 x 256 GB HDD. This SKU will be removed anyhow and replaced with DS15_v2
