### ISSUE TITLE
Issues mentioned via email about createUiDefinition.json

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#22]
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L67 (DBC password should have a better regex and minimum of 8 characters)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L10

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L79 (question mark)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L98

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L699

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L711 (consider DS15_v2)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L729 (provide description of storage for all node configurations)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L892 (not only new is supported)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L902 (not only "new" is supported)

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/createUiDefinition.json#L957 (more explanation is needed here via tool tip and description, otherwise users will not understand)

**Comment by btprabhu** [comment]
Almost all point are fixed.
