### ISSUE TITLE
New tagging requirement

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#23]
Please use the instructions below to add unique tags to ALL solution templates (both Marketplace and non-Marketplace) moving forward – new or updated. After you create and apply the unique GUIDs, please email me the ISV name and GUID so that I can provide it to the proper internal teams.

Step 1: Within the “parameters” section of an ISV’s primary solution template,
(a)	Define a tag as shown below, replacing “<isvname >” with name of the ISV (in your case, "teradata")
(b)	Replace “<guid >” with a GUID value w/ format  “XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX”
•	You can use Visual Studio 2015 Menu “Tools | Create GUID, Registry Format” or
•	You can use https://guidgenerator.com/ but remember to check the ‘Uppcase’ & ‘Hypens’ checkboxes and to uncheck the ‘Braces’ checkbox  before clicking on ‘Generate some GUIDs!’

"parameters": {
…
    "teradataTags": {
      "type": "object",
      "defaultValue": {
        "provider": "<guid>"
      }
    },
…
  }

Step 2: Tag each resource within the “resources” section (and any resources within nested templates) with a tag as follows
"tags": {
         "provider": "[toUpper(parameters('teradataTags').provider)]"
       }

e.g.
"resources": [
…
{ 
       "type": "Microsoft.Network/virtualNetworks", 
       "name": "[variables('virtualNetworkName')]", 
       "location": "[variables('location')]", 
       "apiVersion": "2015-06-15", 
       "tags": { 
         "provider": "[toUpper(parameters('teradataTags').provider)]"
       }, 
},
…
{
       "name": "[variables('chefbeName')]", 
       "type": "Microsoft.Storage/storageAccounts", 
       "location": "[variables('location')]", 
       "apiVersion": "2015-06-15", 
       "dependsOn": [ ], 
       "tags": { 
         "provider": "[toUpper(parameters('teradataTags').provider)]"
       },
       "properties": { 
         "accountType": "[parameters('storageAccountType')]" 
       } 
},

**Comment by btprabhu** [comment]
Hi have used this object as teradata tags :
"teradataTags": {
		  "type": "object",
		  "defaultValue": {
		  "provider": {
			"resources":{
						  "deployments": "489F643A-40C6-49B4-A1BC-467D2F2334EF"
						},
			"storage":  {
						  "storageAccountsDiagnostics": "5F315ADE-167D-4C50-95D4-4BBAF0882B19",
						  "storageAccountsOS":"9ECA3DB7-D642-4CC4-ACD4-AC2DD1167F97",
						  "storageAccountsDatadisk":"2B2D04DC-931D-4FD8-8B16-422C30B17D48"
						},
			"network":  {
						  "virtualNetworks": "643E3585-9531-4CBB-91F9-9717BB198224",
						  "networkInterfaces": "29C8BE70-048B-4501-823E-27DF48924F39",
						  "loadBalancers": "CC705888-08F3-4F0A-97E5-FCB8469623F5",
						  "publicIPAddresses": "D67676FC-E3BC-4F2D-92CC-E5CE381D6A56",
						  "networkSecurityGroups": "662B9F34-970F-4EE1-BF48-3ACFC403F22F"
				        },
			"compute":  {
						  "availabilitySets": "AB0FD642-AB89-4514-A2C1-E9697F6B760C",
						  "virtualMachines": "2AD8FADD-190D-41C8-87BB-9C2DE552CB45",
						  "virtualMachineExtensions": "B3B37C09-CFE6-4403-86E7-A1F174797229"
						}
					  }
		    }
		}

**Comment by btprabhu** [comment]
Done

**Comment by arsenvlad** [comment]
Thank you for the quick implementation! However, I think I didn't clarify the requirement properly.

There should be one single GUID used for any and all of Teradata's templates both for marketplace and for outside of marketplace and the same value should be used for all resources.

So there should be just one parameter with a default value of that GUID. That parameter should flow into all of the nested templates and the value of the parameter should be applied to all resources.

For each resource you would apply it like this:

{
"type": "Microsoft.Network/virtualNetworks",
"name": "[variables('virtualNetworkName')]",
"location": "[variables('location')]",
"apiVersion": "2015-06-15",
"tags": {
"provider": "[toUpper(parameters('teradataTags').provider)]"
},

Notice it is not virtualNetwork specific, just the same provider GUID for all.

**Comment by btprabhu** [comment]
Ok, As in your example your are creating an teradataTags as an object can we simply pass it as string ?

**Comment by arsenvlad** [comment]
They requested it as an object for potential future expand soon to have more sub properties

**Comment by btprabhu** [comment]
Done as per your requirement.
"provider": "1C8BE09A-CE46-4BF1-A01B-F570FE1EA1B3"
