### ISSUE TITLE
UI definition pointing to wrong image

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#26]
createUiDefinition.json is pointing to WRONG image which is probably the reason we see "Unable to display pricing" message on the compute size selector control:
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/cb443f3fed5e6d4cd10d91a9fef6c2417751ddd6/createUiDefinition.json#L725

It is pointing to the mpp-internal-offer1-preview:mpp-image-1 instead of pointing to the beta image.

Can you please fix this and restage? Please whitelist additional subscription that I emailed.

**Comment by btprabhu** [comment]
Fixed
