### ISSUE TITLE
Add allowedValues for vnetNewOrExisting parameter

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#27]
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/cb443f3fed5e6d4cd10d91a9fef6c2417751ddd6/mainTemplate.json#L91

This will prevent issues like Caesar had with New being upper case and causing failures when using templates outside of marketplace.

**Comment by btprabhu** [comment]
Fixed
