### ISSUE TITLE
Consider updating apiVersions to latest and checking

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#4]
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L175

You can get the latest provider versions using the Azure CLI "azure provider list --json" to a file and looking for the latest versions. 

When you changing the versions to the very latest (not preview) for the Microsoft.Network & Microsoft.Storage you may need to tweak the template a bit if the shape of the objects changed.

**Comment by btprabhu** [comment]
Done and update
