### ISSUE TITLE
Change apiVersion for virtualMachines/extensions to 2016-03-30

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#5]
https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L192 seems to be using 2015-05-01-preview. This should change to the latest version 2016-03-30. Is there a specific reason that preview version is used?

**Comment by btprabhu** [comment]
Done
