### ISSUE TITLE
Should not use resourceGroup().location as location

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#7]
Please check all other templates to make sure that resourceGroup().location is not used by the template. We should use the location parameter instead.

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L321

**Comment by btprabhu** [comment]
Done
