### ISSUE TITLE
Purpose of imageStorageAccountType

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#8]
What is this value used for by the templates that use the marketplace image? Is it there just for convenience to make it easier to re purpose the templates for a custom-image deployment instead of marketplace?

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L270

**Comment by btprabhu** [comment]
It is required because different skus have different type OS-storage account
