### ISSUE TITLE
Restricting source IP locations

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/TeradataEnterprise_Beta4.0#9]
Does it make sense to provide a UI parameter (with good RegEx) asking for CIDR (0.0.0.0/0 for all) to restrict outside access to the deployment's public IPs? This parameter could be used to set proper NSG rules.

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L331

https://github.com/btprabhu/TeradataEnterprise_Beta4.0/blob/fdee7bbe22d983210dd73548157e3d666e2833a4/mainTemplate.json#L345

For example:

 {
            "name": "allowedIPAddressPrefix",
            "type": "Microsoft.Common.TextBox",
            "label": "Allowed IP address range",
            "toolTip": "The IP address range (i.e. CIDR) that can be used to access the nodes from the outside of the VNet (0.0.0.0/0 means access is allowed from everywhere)",
            "defaultValue": "0.0.0.0/0",
            "constraints": {
              "required": true,
              "regex": "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$",
              "validationMessage": "Allowed IP address range (i.e. CIDR) must be provided as xxx.xxx.xxx.xxx/xx (e.g. 71.23.14.0/24)"
            }
          }

**Comment by btprabhu** [comment]
As discuss with Prabhu it is not required.
